/** V2 HTTP/WebSocket relay proof.  Each case below ports a v1 relay proof to opaque handles. */
import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import { Store } from "../src/lib/db.ts";
import { FanoutHub, MAX_UPDATE_BYTES } from "../src/lib/matters.ts";
import { buildServeOptions, type SyncSocketData } from "../src/server.ts";
import { SyncTicketStore } from "../src/lib/syncTickets.ts";
import { rateLimit } from "../src/lib/http.ts";

const store = new Store(":memory:"), hub = new FanoutHub();
const server = Bun.serve<SyncSocketData>(buildServeOptions(store, hub));
const base = () => `http://${server.hostname}:${server.port}`;
let admin = "", alice = "", bob = "", carol = "", aliceSeat = "", bobSeat = "", carolSeat = "", aliceId = "", bobId = "", handle = "", root = "", otherHandle = "";
const post = async (path:string, body:unknown = {}, token?:string, extra:Record<string,string> = {}) => {
  const r = await fetch(base()+path,{method:"POST",headers:{"content-type":"application/json",...token?{authorization:`Bearer ${token}`}:{},...extra},body:JSON.stringify(body)});
  return {status:r.status,body:await r.json().catch(()=>({})) as Record<string,any>};
};
const get = async (path:string, token?:string, seat?:string) => { const r=await fetch(base()+path,{headers:{...token?{authorization:`Bearer ${token}`}:{},...seat?{"x-seat-token":seat}:{}}}); return {status:r.status,body:await r.json().catch(()=>({})) as Record<string,any>}; };
const push = (_mh:string,sh:string, token:string,seat:string, blob:string, bytes:Uint8Array, epoch=1) => post(`/v2/firm/streams/${sh}/updates`,{blob_id:blob,ciphertext_b64:Buffer.from(bytes).toString("base64"),seat_token:seat,key_epoch:epoch},token);
const allocateCommitted = async () => { const allocated=await post(`/v2/firm/matters/${handle}/streams`,{},alice,{"x-seat-token":aliceSeat}); const stream=allocated.body.stream_handle as string; const committed=await post(`/v2/firm/streams/${root}/updates`,{blob_id:`root-commits-${crypto.randomUUID()}`,ciphertext_b64:"AQ==",seat_token:aliceSeat,key_epoch:1,commit_stream_handle:stream},alice); expect(committed.status).toBe(201); return stream; };
const pull = (_mh:string,sh:string,token:string,seat:string,since=0) => get(`/v2/firm/streams/${sh}/updates?since=${since}`,token,seat);
const ticket = (_mh:string,sh:string,token:string,seat:string) => post(`/v2/firm/streams/${sh}/sync-ticket`,{},token,{"x-seat-token":seat});
const wsUrl = (t:string) => `ws://${server.hostname}:${server.port}/v2/firm/sync?ticket=${encodeURIComponent(t)}`;
const open = (url:string) => new Promise<WebSocket>((resolve,reject)=>{const ws=new WebSocket(url), timer=setTimeout(()=>reject(new Error("socket timeout")),3000);ws.onopen=()=>{clearTimeout(timer);resolve(ws)};ws.onerror=()=>{clearTimeout(timer);reject(new Error("socket error"))};});

beforeAll(async () => {
  const provision=await post("/admin/org",{name:"Relay test",plan:"practice",packs:["advisor"],seat_limit:8,admin_email:"admin@relay.test",admin_password:"password-123"});
  admin=(await post("/auth/login",{email:"admin@relay.test",password:"password-123"})).body.access_token;
  const make=async(label:string)=>{const email=`${label}@relay.test`;const user=await post("/org/users",{email,password:"password-123"},admin);const auth=(await post("/auth/login",{email,password:"password-123"})).body.access_token;const active=await post("/org/activate",{license_key:provision.body.license_key,machine_id:`machine-${label}`},auth);return {id:user.body.user.user_id,auth,seat:active.body.seat_token};};
  const a=await make("alice"), b=await make("bob"); alice=a.auth;aliceSeat=a.seat;aliceId=a.id;bob=b.auth;bobSeat=b.seat;bobId=b.id;
  const created=await post("/v2/firm/matters",{},admin);handle=created.body.matter_handle;root=created.body.root_stream_handle;await post(`/v2/firm/matters/${handle}/members/add`,{user_id:aliceId,role:"editor"},admin);await post(`/v2/firm/matters/${handle}/members/add`,{user_id:bobId,role:"editor"},admin);await post(`/v2/firm/matters/${handle}/activate`,{},admin);
  const other=await post("/v2/firm/matters",{},admin);otherHandle=other.body.matter_handle;await post(`/v2/firm/matters/${otherHandle}/activate`,{},admin);
  const p2=await post("/admin/org",{name:"Other",plan:"practice",packs:["advisor"],seat_limit:2,admin_email:"admin@other.test",admin_password:"password-123"}); const otherAdmin=(await post("/auth/login",{email:"admin@other.test",password:"password-123"})).body.access_token;const cu=await post("/org/users",{email:"carol@other.test",password:"password-123"},otherAdmin);carol=(await post("/auth/login",{email:"carol@other.test",password:"password-123"})).body.access_token;carolSeat=(await post("/org/activate",{license_key:p2.body.license_key,machine_id:"carol"},carol)).body.seat_token; expect(cu.status).toBe(201);
});
afterAll(()=>server.stop(true));

describe("v2 encrypted relay: preserved HTTP, authorization, cursor, and socket proofs", () => {
  test("member PUSH then another member PULLS byte-identical ciphertext",async()=>{const bytes=new Uint8Array([0,255,128,1]);const r=await push(handle,root,alice,aliceSeat,"blob-roundtrip",bytes);expect(r.status).toBe(201);const out=await pull(handle,root,bob,bobSeat);expect(out.status).toBe(200);expect(Array.from(Buffer.from(out.body.updates.find((u:any)=>u.blob_id==="blob-roundtrip").ciphertext_b64,"base64"))).toEqual(Array.from(bytes));});
  test("duplicate blob is idempotent in its opaque stream",async()=>{const a=await push(handle,root,alice,aliceSeat,"blob-dup",new Uint8Array([1]));const b=await push(handle,root,alice,aliceSeat,"blob-dup",new Uint8Array([9]));expect([201,200]).toContain(a.status);expect(b).toMatchObject({status:200,body:{duplicate:true,cursor:a.body.cursor}});});
  test("cursor pull is strictly after since and ordered, and carries the matter key epoch",async()=>{const before=(await pull(handle,root,alice,aliceSeat)).body.latest_cursor;const ids:number[]=[];for(let i=0;i<3;i++)ids.push((await push(handle,root,alice,aliceSeat,`seq-${i}`,new Uint8Array([i]))).body.cursor);const response=await pull(handle,root,bob,bobSeat,before);expect(response.body.updates.map((u:any)=>u.cursor)).toEqual(ids);expect(response.body.key_epoch).toBe(store.getMatter(handle)!.key_epoch);});
  test("non-member push and pull are 403 and audited",async()=>{const o=store.createUser({org_id:store.getMatter(handle)!.org_id,email:"outside@relay.test",password_hash:"x",role:"member"});const tok=(await import("../src/lib/services.ts")).issueAuthTokens(store,o).access_token;const seat=store.activateSeat({org_id:o.org_id,user_id:o.user_id,machine_id:"o",machine_label:null,seat_limit:8});if(!seat.ok)throw new Error("seat activation failed");const st=(await import("../src/lib/services.ts")).mintSeatToken(store.getOrg(o.org_id)!,o,seat.seat).token;expect((await push(handle,root,tok,st,"out",new Uint8Array([1]))).status).toBe(403);expect((await pull(handle,root,tok,st)).status).toBe(403);expect(store.listAudit(o.org_id).some(e=>e.action==="matter.access.denied")).toBe(true);});
  test("live member socket receives a pushed v2 update",async()=>{const t=await ticket(handle,root,bob,bobSeat);const ws=await open(wsUrl(t.body.ticket));try{const frame=await new Promise<any>((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error("no update")),3000);ws.onmessage=e=>{const f=JSON.parse(String(e.data));if(f.type==="update"&&f.blob_id==="live"){clearTimeout(timer);resolve(f);}};push(handle,root,alice,aliceSeat,"live",new Uint8Array([7]));});expect(frame).toMatchObject({type:"update",blob_id:"live"});expect(frame).not.toHaveProperty("stream_handle");}finally{ws.close();}});
  test("wall overrides membership for WebSocket upgrade",async()=>{await post(`/v2/firm/matters/${handle}/wall/set`,{user_id:bobId},admin);const t=await ticket(handle,root,bob,bobSeat);expect(t.status).toBe(403);await post(`/v2/firm/matters/${handle}/wall/clear`,{user_id:bobId},admin);});
  test("walled member is rejected on push and pull",async()=>{await post(`/v2/firm/matters/${handle}/wall/set`,{user_id:aliceId},admin);expect((await push(handle,root,alice,aliceSeat,"wall",new Uint8Array([1]))).status).toBe(403);expect((await pull(handle,root,alice,aliceSeat)).status).toBe(403);await post(`/v2/firm/matters/${handle}/wall/clear`,{user_id:aliceId},admin);});
  test("cross-org relay access is a non-enumerating 404",async()=>{expect((await push(handle,root,carol,carolSeat,"cross",new Uint8Array([1]))).status).toBe(404);expect((await pull(handle,root,carol,carolSeat)).status).toBe(404);});
  test("relay requires a valid seat token",async()=>{expect((await post(`/v2/firm/streams/${root}/updates`,{blob_id:"no-seat",ciphertext_b64:"AQ=="},alice)).status).toBe(401);});
  test("relay rejects oversized ciphertext",async()=>{expect((await push(handle,root,alice,aliceSeat,"large",new Uint8Array(MAX_UPDATE_BYTES+1))).status).toBe(413);});
  test("relay rejects malformed v2 payload",async()=>{expect((await post(`/v2/firm/streams/${root}/updates`,{blob_id:"bad",ciphertext_b64:42,seat_token:aliceSeat},alice)).status).toBe(400);});
  test("relay requires authentication",async()=>{expect((await post(`/v2/firm/streams/${root}/updates`,{})).status).toBe(401);});
  test("sync ticket requires access JWT",async()=>{expect((await post(`/v2/firm/streams/${root}/sync-ticket`,{})).status).toBe(401);});
  test("sync ticket requires active seat",async()=>{expect((await post(`/v2/firm/streams/${root}/sync-ticket`,{},alice)).status).toBe(401);});
  test("sync ticket rejects non-member",async()=>{expect((await ticket(handle,root,carol,carolSeat)).status).toBe(404);});
  test("ticket redeems exactly once",async()=>{const t=await ticket(handle,root,bob,bobSeat);const ws=await open(wsUrl(t.body.ticket));ws.close();await new Promise(r=>setTimeout(r,10));await expect(open(wsUrl(t.body.ticket))).rejects.toThrow();});
  test("socket URL carries ticket only",async()=>{const t=await ticket(handle,root,bob,bobSeat);const u=wsUrl(t.body.ticket);expect(u).toMatch(/\/v2\/firm\/sync\?ticket=/);expect(u).not.toContain(handle);expect(u).not.toContain(root);expect(u).not.toContain(bobSeat);expect(u).not.toContain(bob);});
  test("expired ticket is rejected",()=>{const tickets=new SyncTicketStore(-1);const t=tickets.mint({matterHandle:handle,streamHandle:root,orgId:store.getMatter(handle)!.org_id,userId:bobId,seatId:"seat",role:"member"});expect(tickets.redeem(t.ticket)).toBeNull();});
  test("ticket binding carries the requested opaque stream",()=>{const tickets=new SyncTicketStore();const t=tickets.mint({matterHandle:handle,streamHandle:root,orgId:store.getMatter(handle)!.org_id,userId:bobId,seatId:"seat",role:"member"});expect(tickets.redeem(t.ticket)).toMatchObject({matterHandle:handle,streamHandle:root});});
  test("pull requires X-Seat-Token header",async()=>{expect((await get(`/v2/firm/streams/${root}/updates?since=0`,alice)).status).toBe(401);});
  test("normal rate-limit bucket permits a request",()=>expect(rateLimit(`relay-${crypto.randomUUID()}`,"proof",{max:2,windowSeconds:10}).ok).toBe(true));
  test("rate-limit exhaustion has 429 semantics",()=>{const ip=`relay-${crypto.randomUUID()}`;rateLimit(ip,"proof",{max:1,windowSeconds:10});expect(rateLimit(ip,"proof",{max:1,windowSeconds:10}).ok).toBe(false);});
  test("new matter root stream is its opaque notes stream equivalent",()=>expect(root).toMatch(/^sh2_[A-Za-z0-9_-]{43}$/));
  test("allocated document stream is opaque and distinct",async()=>{const r=await post(`/v2/firm/matters/${handle}/streams`,{},alice,{"x-seat-token":aliceSeat});expect(r).toMatchObject({status:201});expect(r.body.stream_handle).toMatch(/^sh2_/);expect(r.body.stream_handle).not.toBe(root);});
  test("streams isolate updates even with the same blob id",async()=>{const s=await allocateCommitted();await push(handle,root,alice,aliceSeat,"same",new Uint8Array([1]));await push(handle,s,alice,aliceSeat,"same",new Uint8Array([2]));expect((await pull(handle,s,bob,bobSeat)).body.updates.some((u:any)=>u.blob_id==="same"&&u.ciphertext_b64==="Ag==")).toBe(true);});
  test("stream cursor is independent",async()=>{const s=await allocateCommitted();expect((await pull(handle,s,bob,bobSeat)).body.latest_cursor).toBe(0);});
  test("pull response omits legacy matter and document fields",async()=>{const body=JSON.stringify((await pull(handle,root,bob,bobSeat)).body);expect(body).not.toContain("matter_id");expect(body).not.toContain("doc_id");});
  test("push response omits route handles",async()=>{const body=JSON.stringify((await push(handle,root,alice,aliceSeat,`no-route-${crypto.randomUUID()}`,new Uint8Array([1]))).body);expect(body).not.toContain("matter_handle");expect(body).not.toContain("stream_handle");});
  test("fan-out frames omit legacy route identifiers",async()=>{const frames:any[]=[];hub.subscribe(handle,{id:"proof",user_id:bobId,seat_id:"s",send:f=>frames.push(f)},root);hub.broadcast(handle,{type:"update",cursor:1,blob_id:"x",key_epoch:1,author_seat:"s",created_at:"now",ciphertext_b64:"AQ=="},root);expect(JSON.stringify(frames)).not.toMatch(/matter_handle|stream_handle|matter_id|doc_id/);hub.unsubscribe(handle,"proof",root);});
  test("ready frame has subscriber count",async()=>{const t=await ticket(handle,root,bob,bobSeat);const ws=await open(wsUrl(t.body.ticket));try{const ready=await new Promise<any>((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error("no ready")),3000);ws.onmessage=e=>{const f=JSON.parse(String(e.data));if(f.type==="ready"){clearTimeout(timer);resolve(f);}}});expect(ready.subscribers).toBeGreaterThan(0);}finally{ws.close();}});
  test("two sockets receive presence count two",async()=>{const a=await ticket(handle,root,alice,aliceSeat),b=await ticket(handle,root,bob,bobSeat);const one=await open(wsUrl(a.body.ticket)),two=await open(wsUrl(b.body.ticket));try{const p=await new Promise<any>((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error("no presence")),3000);one.onmessage=e=>{const f=JSON.parse(String(e.data));if(f.type==="presence"&&f.count>=2){clearTimeout(timer);resolve(f)}}});expect(p.count).toBe(2);}finally{one.close();two.close();}});
  test("remaining socket sees presence one after peer closes",async()=>{const a=await ticket(handle,root,alice,aliceSeat),b=await ticket(handle,root,bob,bobSeat);const one=await open(wsUrl(a.body.ticket)),two=await open(wsUrl(b.body.ticket));try{const p=new Promise<any>((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error("no presence")),3000);one.onmessage=e=>{const f=JSON.parse(String(e.data));if(f.type==="presence"&&f.count===1){clearTimeout(timer);resolve(f)}}});two.close();expect((await p).count).toBe(1);}finally{one.close();}});
  test("presence is stream-isolated",async()=>{const s=await allocateCommitted();const t=await ticket(handle,s,alice,aliceSeat);const ws=await open(wsUrl(t.body.ticket));try{const frames:any[]=[];ws.onmessage=e=>frames.push(JSON.parse(String(e.data)));await new Promise(r=>setTimeout(r,30));expect(frames.filter(f=>f.type==="presence").every(f=>f.count===1)).toBe(true);}finally{ws.close();}});
  test("v1 relay endpoints return deliberate upgrade response",async()=>expect((await post("/matter/matter-semantic-123/updates",{client_name:"x",doc_id:"d"},alice)).status).toBe(426));
  test("v2 rejects a legacy client_name payload",async()=>expect((await post("/v2/firm/matters",{client_name:"x"},admin)).status).toBe(400));
  test("v2 rejects legacy matter_id and doc_id payload",async()=>expect((await post(`/v2/firm/streams/${root}/updates`,{matter_id:"x",doc_id:"y",blob_id:"legacy-fields",ciphertext_b64:"AQ==",seat_token:aliceSeat,key_epoch:1},alice)).status).toBe(400));
  test("nested stream routes are no longer accepted",async()=>{expect((await post(`/v2/firm/matters/${handle}/streams/${root}/updates`,{},alice)).status).toBe(404);expect((await get(`/v2/firm/matters/${handle}/streams/${root}/updates?since=0`,alice,aliceSeat)).status).toBe(400);expect((await post(`/v2/firm/matters/${handle}/streams/${root}/sync-ticket`,{},alice,{"x-seat-token":aliceSeat})).status).toBe(404);});
});
