export {
  CONTACT_KINDS,
  contactTypeAppliesTo,
  contactInputDocument,
  contactRecordFromDocument,
  displayNameFor,
  isContactKind,
  toRecordRef,
  validateContactChannels,
  validateContactCreate,
  validateContactLinks,
  validateContactPatch,
  validateContactRef,
  validateContactTypeDefinition,
} from './model';
export { adaptLegacyHouseholdRecord } from './legacy';
export {
  openContactRef,
  readAskContactSources,
  type AskContactSourcesBoundary,
} from './askSources';
export {
  createContactRecordStore,
  projectContactPrint,
  projectDirectoryContacts,
  projectRecordScreen,
  projectRelatedContactSummary,
  useContactRecordStore,
  type ContactRecordStore,
} from './store';
export type {
  ContactChannel,
  ContactCore,
  ContactCreateInput,
  ContactDirectoryProjection,
  ContactKind,
  ContactLink,
  ContactPatch,
  ContactPrintProjection,
  ContactRecord,
  ContactRef,
  ContactTypeDefinition,
  ContactTypeProjection,
  HouseholdContactRecord,
  LegacyEmbeddedContactProjection,
  OrganizationContactRecord,
  PersonContactRecord,
  RecordScreenProjection,
  RelatedContactProjection,
  RelatedContactSummaryProjection,
  TrustContactRecord,
} from './types';
