// Advisor Practice Pack v1.0 (shipped). Built with input from practicing advisors.
// Drafting aid: every generated output carries a banner requiring professional review before use.
// COMPLIANCE SENSITIVE: Rule 204-2 record retention. Must be reviewed by qualified compliance professional before use.

import type { WorkflowTemplate, InterviewStepConfig, GenerateStepConfig } from '@/platform/types/workflow';
import { BRAND } from '@/config/brand';

const interviewQuestions: InterviewStepConfig['questions'] = [
  {
    id: 'firmSize',
    question: 'Firm size',
    description: 'Describe your firm: registration, number of advisors, and approximate AUM.',
    type: 'textarea',
    required: true,
    placeholder: 'e.g., RIA, SEC-registered, 3 advisors, $180M AUM. Solo principal with 2 support staff.',
  },
  {
    id: 'accountTypes',
    question: 'Account types handled',
    description: 'What types of accounts and clients does your firm serve?',
    type: 'textarea',
    required: true,
    placeholder: 'e.g., Individual brokerage accounts, IRAs (traditional and Roth), trust accounts, 401(k) rollovers. No institutional or ERISA plan clients.',
  },
  {
    id: 'currentRecordSystems',
    question: 'Current record systems',
    description: 'What systems do you use to maintain client records? Include CRM, portfolio management, file storage, email, financial planning software, and AI tools.',
    type: 'textarea',
    required: true,
    placeholder: `e.g., Orion (portfolio management, transaction records), Salesforce (CRM, notes, correspondence), SharePoint / OneDrive (document storage), Microsoft 365 (email), ${BRAND.name} (AI-assisted client workflows and outputs), MoneyGuide Pro (financial plans)`,
  },
  {
    id: 'currentRetentionPractice',
    question: 'Current retention practice (if any)',
    description: 'How do you currently organize and retain client records? Any written policy, folder conventions, or archiving procedures.',
    type: 'textarea',
    required: false,
    placeholder: 'e.g., Client folders in SharePoint organized by client last name. No written retention policy. Email archived automatically by Microsoft 365 for 3 years. No systematic AI output retention process.',
  },
  {
    id: 'specificConcerns',
    question: 'Specific concerns or areas to address (optional)',
    description: 'Any specific retention questions or gaps you want the guide to address.',
    type: 'textarea',
    required: false,
    placeholder: `e.g., How to handle ${BRAND.messaging.redlineAuthor} output files. What to retain when a client terminates. State-specific retention requirements for California clients.`,
  },
];

const booksRecordsRetentionPrompt = `You are assisting a financial advisor in producing a client-file retention guide that documents a retention practice for ${BRAND.name} files and other client records, supporting Rule 204-2 compliance. This guide documents a practice — it does not create compliance on its own, it does not create a WORM-compliant system, and it does not substitute for legal counsel on the firm's specific obligations.

Firm size: {{firmSize}}
Account types handled: {{accountTypes}}
Current record systems: {{currentRecordSystems}}
Current retention practice: {{currentRetentionPractice}}
Specific concerns: {{specificConcerns}}

Produce a client-file retention guide in Markdown. At the top, include the compliance notice.

> **This guide documents a retention practice. It does not create a WORM-compliant system, satisfy Rule 204-2 on its own, or substitute for legal counsel on your firm's specific retention obligations. Have a compliance professional or securities attorney review this guide and confirm it is appropriate for your firm before relying on it.**

---

# Client-File Retention Guide
**COMPLIANCE DRAFT — Requires review before implementation.**

**Firm:** [Firm name — complete before use]
**Prepared:** [date]
**Rule reference:** Investment Advisers Act Rule 204-2 (17 CFR 240.204-2)

---

## What This Document Is (and Is Not)

This guide describes how [Firm name] organizes and retains client records, including records generated by AI-assisted workflows in ${BRAND.name}. It documents the firm's retention practice to support Rule 204-2 compliance.

**What this guide does:**
- Establishes a consistent per-client folder convention for ${BRAND.name} files and other client documents
- Provides a retention period table by record type, keyed to Rule 204-2 and state requirements
- Describes how to export and archive AI activity logs from ${BRAND.name}
- Provides a quarterly review checklist

**What this guide does not do:**
- This guide does not create a WORM-compliant (Write Once, Read Many) electronic record system. If your firm is required to maintain records in a WORM-compliant system, consult your compliance professional.
- This guide does not satisfy Rule 204-2 on its own. Rule 204-2 sets specific requirements for what must be retained, for how long, and in what format. This guide is a starting framework, not a compliance certification.
- This guide does not address all state-specific retention requirements. If your firm has clients in states with additional retention requirements, consult a securities attorney licensed in those states.
- This guide does not substitute for legal counsel on your firm's specific obligations.

---

## Part 1: Per-Client Folder Convention for ${BRAND.name} Files

[Produce a recommended folder structure for organizing client records in ${BRAND.name} and the document storage system, based on the systems provided:]

### Recommended Per-Client Folder Structure

    [Client Last Name, First Name] - [Account Number or Client ID]
    |-- 00_Client_Profile
    |   |-- KYC_and_Suitability/
    |   |-- IPS_and_Goals/
    |   +-- Beneficiary_and_Estate/
    |-- 01_Financial_Plans
    |   +-- [YYYY-MM-DD]_[PlanName].md  (or .pdf)
    |-- 02_AI_Workflow_Outputs
    |   +-- [YYYY-MM-DD]_[TemplateName]_output.md
    |-- 03_Meeting_Notes_and_Correspondence
    |   +-- [YYYY-MM-DD]_[MeetingType]_notes.md
    |-- 04_Account_Records
    |   |-- Statements/
    |   +-- Transaction_Records/
    +-- 05_Archive
        +-- [Records no longer active but within retention period]

**Naming conventions:**
- All files prefixed with ISO date (YYYY-MM-DD) for sortability
- AI workflow outputs go in the 02_AI_Workflow_Outputs/ folder — see Part 3 for export procedure
- Terminated clients: move to a _TERMINATED/[ClientName] folder, retain per the retention table in Part 2

---

## Part 2: Retention Period Table

[Produce a retention period table keyed to Rule 204-2 requirements. Note clearly where state requirements may extend federal minimums:]

| Record type | Federal minimum (Rule 204-2) | Recommended practice | Notes |
|---|---|---|---|
| Investment advisory contracts | 5 years from end of fiscal year | 7 years | First 2 years in accessible storage |
| Written financial plans | 5 years | 7 years | Includes AI-generated plan outputs |
| AI workflow outputs (all categories) | 5 years (correspondence and records) | 7 years | Export from ${BRAND.name} — see Part 3 |
| Client correspondence (email, letters) | 5 years | 7 years | Includes digital correspondence |
| Meeting notes and memoranda | 5 years | 7 years | |
| Suitability / KYC documentation | 5 years | 7 years | Update when client circumstances change |
| Trade order records | 5 years | 7 years | First 2 years in accessible storage |
| Account statements | 5 years | 7 years | |
| Billing records and invoices | 5 years | 7 years | |
| Form ADV and amendments | 5 years | 7 years | |
| Compliance policies and procedures | 5 years | 7 years | |
| Code of ethics and access persons records | 5 years | 7 years | |
| Proxy voting records (if applicable) | 3 years | 5 years | |
| Marketing materials and advertisements | 5 years | 7 years | Includes website and social media records |

**[COMPLIANCE NOTE]** This table reflects general Rule 204-2 requirements. State investment adviser laws in any states reflected in the account and client description ({{accountTypes}}) may impose longer retention periods. Verify state requirements with a securities attorney before finalizing this table.

**"Accessible storage" note:** Rule 204-2 requires that records for the first two years of the retention period be maintained in an "easily accessible place." Confirm with your compliance professional what systems satisfy this requirement for your firm.

---

## Part 3: Per-Client AI Activity Log Export Guide

[Produce step-by-step instructions for exporting and archiving ${BRAND.messaging.redlineAuthor} workflow outputs as part of the client file:]

### When to Export

Export ${BRAND.name} workflow outputs to the client file:
- After every completed workflow run that produces a client-facing document
- At the end of each calendar quarter (catch-all)
- When a client terminates (before closing the client file)
- At the end of each fiscal year

### Export Procedure

1. In ${BRAND.name}, navigate to the client's workspace or project.
2. Locate the completed workflow output(s) for the period.
3. Export each output as a Markdown (.md) or PDF file.
4. Name the file using the format: YYYY-MM-DD_TemplateName_output.md (or .pdf) (e.g., 2026-05-14_AnnualReviewPacket_output.pdf)
5. Save to the client's 02_AI_Workflow_Outputs/ folder in your document storage system.
6. Note the export in the client's activity log (see quarterly review checklist below).

### What to Export

Export all completed ${BRAND.name} workflow outputs, including:
- Annual review packets
- Financial plan summaries
- Meeting prep and suitability notes
- Any template output used in a client meeting or sent to a client

**[COMPLIANCE NOTE]** If a ${BRAND.name} output was reviewed and edited before client delivery, retain both the AI-generated draft and the final version delivered to the client.

---

## Part 4: Quarterly Review Checklist

[Produce a quarterly review checklist that the advisor runs to keep the retention practice current:]

### Quarterly Client-File Retention Review

**Quarter:** [Q1 / Q2 / Q3 / Q4] [Year]
**Completed by:** [Name / role]
**Date completed:** [Date]

| Item | Completed | Notes |
|---|---|---|
| Export all ${BRAND.messaging.redlineAuthor} outputs since last review to client files | | |
| Confirm all new client correspondence filed in client folders | | |
| Confirm all meeting notes filed and dated | | |
| Review any client terminations — confirm terminated-client files moved to archive | | |
| Purge any records beyond retention period (per retention table, Part 2) — document what was purged | | |
| Confirm backup of document storage system completed this quarter | | |
| Review for any new client suitability changes that require updated KYC documentation | | |
| Confirm no records in accessible storage are past the 2-year accessible-storage period | | |

**Purge log for this quarter:**

| Record type | Client(s) | Date range purged | Purged by | Date of purge |
|---|---|---|---|---|
| | | | | |

---

*This guide documents a retention practice and does not create a WORM-compliant system, satisfy Rule 204-2 on its own, or substitute for legal counsel. Have a compliance professional review this guide before implementing it.*`;

export const BooksRecordsRetentionNote: WorkflowTemplate = {
  id: 'advisors-books-records-retention-note',
  name: 'Books and Records Retention Documentation',
  description: "Structures per-client folder conventions and retention export documentation supporting Rule 204-2 compliance. Produces a client-file retention guide honest about what it does and does not satisfy.",
  version: '1.0.0',
  category: 'advisors',
  requiresVerification: true,
  verificationNote: 'This template documents a retention practice; it does not create a WORM-compliant system, satisfy Rule 204-2 on its own, or substitute for legal counsel on your firm\'s specific retention obligations.',
  steps: [
    {
      id: 'interview',
      type: 'interview',
      name: 'Firm and Records Information',
      description: 'Provide your firm size, account types, record systems, and current retention practice',
      config: {
        questions: interviewQuestions,
      } as InterviewStepConfig,
    },
    {
      id: 'generate-retention-guide',
      type: 'generate',
      name: 'Generate Books and Records Retention Guide',
      description: 'Produce a per-client folder convention, retention period table, AI activity log export guide, and quarterly review checklist',
      config: {
        outputFile: 'BOOKS_RECORDS_RETENTION_GUIDE.md',
        promptTemplate: booksRecordsRetentionPrompt,
        systemPrompt: `You are a financial advisory compliance assistant helping an RIA produce a client-file retention guide to support Rule 204-2 compliance. You are careful and honest: this guide documents a practice, it is not a compliance certification, it does not create a WORM-compliant system, and it does not substitute for legal counsel. You surface these limitations prominently. The retention period table reflects general Rule 204-2 requirements with a note that state requirements may be longer. The ${BRAND.messaging.redlineAuthor} output export section is specific and practical — it gives the advisor a step-by-step procedure they can actually follow. The quarterly checklist is comprehensive enough to catch gaps. You never overstate what this document satisfies.`,
      } as GenerateStepConfig,
    },
  ],
  requiredInputs: [],
  outputs: ['BOOKS_RECORDS_RETENTION_GUIDE.md'],
  namedOutputs: [
    { id: 'folder_convention', name: 'Per-client folder convention', schema: 'string' },
    { id: 'retention_table', name: 'Retention period table', schema: 'string' },
    { id: 'ai_export_guide', name: 'AI activity log export guide', schema: 'string' },
  ],
};

export default BooksRecordsRetentionNote;
