//! Task 5: blank-doc regression.
//!
//! A document created by `createBlankDocx()` (the TS helper) must, when opened
//! through the real Rust engine, produce at least ONE editable paragraph block
//! and ZERO preserved (Raw) blocks. Any Raw block would render in the editor as
//! a read-only placeholder, which is what the user reported for a freshly-created
//! blank Word document.
//!
//! The fixture path is generated by the TS test helper and committed as
//! `tests/fixtures/blank-from-frontend.docx`. The Rust test reads it through
//! the public API and asserts the contract.

use std::io::Write as _;

use keepance_docx::{open_docx_bytes, BlockContent};

/// Helper: count paragraphs vs raw blocks in the body.
fn count_blocks(body: &[BlockContent]) -> (usize, usize) {
    body.iter().fold((0, 0), |(paras, raws), block| match block {
        BlockContent::Paragraph(_) => (paras + 1, raws),
        BlockContent::Raw { .. } => (paras, raws + 1),
    })
}

/// Build a minimal `.docx` zip whose body contains only the given `body_xml`
/// fragment (everything between `<w:body>` and `</w:body>`).
///
/// Uses the same plumbing constants the engine emits for new packages so the
/// package is spec-correct but contains a hand-crafted body, which lets us
/// inject unusual-but-valid OOXML patterns (e.g. `<w:p/>` self-closing).
fn build_docx_with_body(body_xml: &str) -> Vec<u8> {
    use zip::write::SimpleFileOptions;
    use zip::{CompressionMethod, ZipWriter};

    let w_ns = "http://schemas.openxmlformats.org/wordprocessingml/2006/main";
    let rel_ns = "http://schemas.openxmlformats.org/package/2006/relationships";
    let doc_rel = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument";

    let document_xml = format!(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="{w_ns}"><w:body>{body_xml}</w:body></w:document>"#,
    );
    let content_types = format!(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>"#,
    );
    let root_rels = format!(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="{rel_ns}"><Relationship Id="rId1" Type="{doc_rel}" Target="word/document.xml"/></Relationships>"#,
    );
    let word_rels = format!(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="{rel_ns}"/>"#,
    );

    let buf = Vec::new();
    let mut zw = ZipWriter::new(std::io::Cursor::new(buf));
    let opts = SimpleFileOptions::default()
        .compression_method(CompressionMethod::Stored)
        .unix_permissions(0o644);

    zw.start_file("[Content_Types].xml", opts).unwrap();
    zw.write_all(content_types.as_bytes()).unwrap();
    zw.start_file("_rels/.rels", opts).unwrap();
    zw.write_all(root_rels.as_bytes()).unwrap();
    zw.start_file("word/document.xml", opts).unwrap();
    zw.write_all(document_xml.as_bytes()).unwrap();
    zw.start_file("word/_rels/document.xml.rels", opts).unwrap();
    zw.write_all(word_rels.as_bytes()).unwrap();

    zw.finish().unwrap().into_inner()
}

// ---------------------------------------------------------------------------
// Item 4: self-closing <w:p/> coverage
// ---------------------------------------------------------------------------

/// A self-closing `<w:p/>` (Word's compact empty-paragraph notation) must parse
/// into an editable Paragraph block, NOT a preserved Raw block. The
/// `Event::Empty` branch in `parse_body` (parse.rs) handles this; without it,
/// `<w:p/>` would fall through to the else branch and be captured as Raw, making
/// the paragraph appear as a read-only "[preserved content]" placeholder.
///
/// Reverting the `Event::Empty` fix in parse.rs (i.e. removing the `if ln == "p"`
/// branch so all empty body elements fall through to Raw) would cause this test
/// to fail: the body would contain 0 Paragraph blocks and 1 Raw block.
#[test]
fn self_closing_wp_parses_as_editable_paragraph_not_raw() {
    // Word emits `<w:p w:rsidR="00AB12CD"/>` for structural empty paragraphs;
    // our minimal docx uses the bare `<w:p/>` which is equivalent.
    let bytes = build_docx_with_body("<w:p w:rsidR=\"00AB12CD\"/>");
    let opened = open_docx_bytes(&bytes).expect("parse self-closing <w:p/>");

    let (paras, raws) = count_blocks(&opened.document.body);

    assert_eq!(
        paras, 1,
        "self-closing <w:p/> must parse as 1 Paragraph block (Event::Empty fix in parse.rs); \
         got {paras} paragraphs, {raws} raw blocks"
    );
    assert_eq!(
        raws, 0,
        "self-closing <w:p/> must produce 0 Raw blocks; \
         got {paras} paragraphs, {raws} raw blocks"
    );
}

/// A blank document created by `createBlankDocx()` must parse into a model that
/// has at least one editable paragraph block and NO preserved (Raw) blocks.
/// Raw blocks are what the editor renders as "[preserved content]" placeholders.
#[test]
fn blank_frontend_doc_has_editable_paragraph_and_no_raw_blocks() {
    let fixture_path =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/blank-from-frontend.docx");
    assert!(
        fixture_path.exists(),
        "fixture not found at {:?} — run the TS fixture-writer first: npx vitest run tests/unit/docx-blank-create.test.ts",
        fixture_path
    );

    let bytes = std::fs::read(&fixture_path).expect("read fixture");
    let opened = open_docx_bytes(&bytes).expect("parse fixture");

    let (paras, raws) = count_blocks(&opened.document.body);

    assert!(
        paras >= 1,
        "blank doc must have at least one editable paragraph; got {paras} paragraphs, {raws} raw blocks"
    );
    assert_eq!(
        raws, 0,
        "blank doc must have 0 raw blocks (the editor renders these as \
         read-only placeholders); got {paras} paragraphs, {raws} raw blocks"
    );
}
