/** Wrapped-key routes keyed only by opaque `mh2_` handles. */
import { json, error, isNonEmptyString, authenticate } from "../lib/http.ts";
import { readStrictV2Payload } from "../lib/v2Payload.ts";
import { verifyActiveSeat } from "../lib/matters.ts";
import type { Store } from "../lib/db.ts";

const valid = (h:string) => /^mh2_[A-Za-z0-9_-]{43}$/.test(h);
function authSeat(req:Request,store:Store) { const a=authenticate(req);if(!a.ok)return {ok:false as const,resp:error("unauthorized",401,a.reason)};const token=req.headers.get("x-seat-token");if(!token)return {ok:false as const,resp:error("seat_required",401)};const s=verifyActiveSeat(store,token,{user_id:a.claims.sub,org_id:a.claims.org_id});return s.ok?{ok:true as const,claims:a.claims}:{ok:false as const,resp:error("seat_invalid",401,s.reason)}; }
export async function handlePublishMatterKeys(req:Request,store:Store,handle:string):Promise<Response> { const a=authenticate(req);if(!a.ok)return error("unauthorized",401,a.reason);if(!valid(handle))return error("matter_not_found",404);const m=store.getMatter(handle);if(!m||m.org_id!==a.claims.org_id)return error("matter_not_found",404);if(store.isWalled(handle,a.claims.sub))return error("forbidden",403,"walled");const own=store.getMatterMember(handle,a.claims.sub)?.role==="owner";if(a.claims.role!=="admin"&&!own)return error("forbidden",403,"admin_or_owner_required");const b=await readStrictV2Payload(req,["epoch","wrapped"]);if(!b||!Number.isInteger(b.epoch)||typeof b.epoch!=="number"||!Array.isArray(b.wrapped)||b.wrapped.some((item)=>!item||typeof item!=="object"||Array.isArray(item)||Object.keys(item as Record<string,unknown>).some((key)=>!["user_id","device_id","wrapped_key_b64"].includes(key))))return error("invalid_v2_payload",400);if(b.epoch!==m.key_epoch)return error("stale_epoch",409);let stored=0,skipped=0;for(const item of b.wrapped){const e=item as Record<string,unknown>;if(!isNonEmptyString(e.user_id,64)||!isNonEmptyString(e.device_id,128)||!isNonEmptyString(e.wrapped_key_b64,16384))return error("invalid_v2_payload",400);const u=store.getUser(e.user_id);if(!u||u.org_id!==a.claims.org_id||store.isWalled(handle,e.user_id)){skipped++;continue;}store.upsertWrappedMatterKey({matter_handle:handle,epoch:b.epoch,user_id:e.user_id,device_id:e.device_id,wrapped_key_b64:e.wrapped_key_b64,published_by:a.claims.sub});stored++;}store.audit({org_id:a.claims.org_id,actor_user_id:a.claims.sub,action:"matter.keys.publish",target:handle,detail:{op:"key_publish",epoch:b.epoch,stored,skipped}});return json({ok:true,stored}); }
export async function handleFetchMatterKey(req:Request,store:Store,handle:string):Promise<Response> { const a=authSeat(req,store);if(!a.ok)return a.resp;if(!valid(handle))return error("matter_not_found",404);const m=store.getMatter(handle);if(!m||m.org_id!==a.claims.org_id)return error("matter_not_found",404);if(store.isWalled(handle,a.claims.sub))return error("forbidden",403,"walled");if(!store.getMatterMember(handle,a.claims.sub)&&a.claims.role!=="admin")return error("forbidden",403,"not_member");const b=await readStrictV2Payload(req,["device_id"]);if(!b||!isNonEmptyString(b.device_id,128))return error("invalid_v2_payload",400);const row=store.getWrappedMatterKey(handle,m.key_epoch,a.claims.sub,b.device_id);if(!row)return error("not_published",404);store.audit({org_id:a.claims.org_id,actor_user_id:a.claims.sub,action:"matter.keys.fetch",target:handle,detail:{op:"key_fetch",epoch:m.key_epoch}});return json({epoch:m.key_epoch,wrapped_key_b64:row.wrapped_key_b64}); }
export async function handleMatterMine(req:Request,store:Store):Promise<Response> { const a=authSeat(req,store);if(!a.ok)return a.resp;if(await readStrictV2Payload(req,[])===null)return error("invalid_v2_payload",400);return json({matters:store.listMatterMembershipsForUser(a.claims.sub,a.claims.org_id)}); }
