/** Wrapped-key routes keyed only by opaque `mh2_` handles. */
import { json, error, isNonEmptyString, authenticate } from "../lib/http.ts";
import { readStrictV2Payload } from "../lib/v2Payload.ts";
import { v2BodyKeys } from "../lib/v2RouteInventory.ts";
import { verifyActiveSeat } from "../lib/matters.ts";
import { decodeWrappedKeyEnvelope, encodeWrappedKeyEnvelope, MAX_WRAPPED_KEYS_PER_PUBLISH } from "../lib/wrappedKeyEnvelope.ts";
import type { Store } from "../lib/db.ts";

const valid = (h:string) => /^mh2_[A-Za-z0-9_-]{43}$/.test(h);
function authSeat(req:Request,store:Store) { const a=authenticate(req);if(!a.ok)return {ok:false as const,resp:error("unauthorized",401,a.reason)};const token=req.headers.get("x-seat-token");if(!token)return {ok:false as const,resp:error("seat_required",401)};const s=verifyActiveSeat(store,token,{user_id:a.claims.sub,org_id:a.claims.org_id});return s.ok?{ok:true as const,claims:a.claims}:{ok:false as const,resp:error("seat_invalid",401,s.reason)}; }
export async function handlePublishMatterKeys(req:Request,store:Store,handle:string):Promise<Response> { const a=authenticate(req);if(!a.ok)return error("unauthorized",401,a.reason);if(!valid(handle))return error("matter_not_found",404);const b=await readStrictV2Payload(req,v2BodyKeys("publishMatterKeys"));if(!b||!Number.isInteger(b.epoch)||typeof b.epoch!=="number"||!Array.isArray(b.wrapped)||b.wrapped.length>MAX_WRAPPED_KEYS_PER_PUBLISH||b.wrapped.some((item)=>!item||typeof item!=="object"||Array.isArray(item)||Object.keys(item as Record<string,unknown>).some((key)=>!["user_id","device_id","wrapped_key_b64"].includes(key))))return error("invalid_v2_payload",400);const wrapped:Array<{user_id:string;device_id:string;wrapped_key:Uint8Array}>=[];for(const item of b.wrapped){const e=item as Record<string,unknown>;const envelope=decodeWrappedKeyEnvelope(e.wrapped_key_b64);if(!isNonEmptyString(e.user_id,64)||!isNonEmptyString(e.device_id,128)||!envelope||!store.getDevice(e.device_id,e.user_id))return error("invalid_v2_payload",400);wrapped.push({user_id:e.user_id,device_id:e.device_id,wrapped_key:envelope});}const m=store.getMatter(handle);if(!m||m.org_id!==a.claims.org_id)return error("matter_not_found",404);if(store.isWalled(handle,a.claims.sub))return error("forbidden",403,"walled");const own=store.getMatterMember(handle,a.claims.sub)?.role==="owner";if(a.claims.role!=="admin"&&!own)return error("forbidden",403,"admin_or_owner_required");const published=store.publishWrappedMatterKeys({matter_handle:handle,org_id:a.claims.org_id,epoch:b.epoch,published_by:a.claims.sub,wrapped});if("matterArchived" in published||"matterNotFound" in published)return error("matter_not_found",404);if("publisherWalled" in published)return error("forbidden",403,"walled");if("publisherUnauthorized" in published)return error("forbidden",403,"admin_or_owner_required");if("invalidRecipient" in published)return error("invalid_v2_payload",400);if("staleEpoch" in published)return error("stale_epoch",409);store.audit({org_id:a.claims.org_id,actor_user_id:a.claims.sub,action:"matter.keys.publish",target:handle,detail:{op:"key_publish",epoch:b.epoch,stored:published.stored,skipped:published.skipped}});return json({ok:true,stored:published.stored}); }
export async function handleFetchMatterKey(req:Request,store:Store,handle:string):Promise<Response> { if(!valid(handle))return error("matter_not_found",404);const b=await readStrictV2Payload(req,v2BodyKeys("fetchMatterKey"));const a=authSeat(req,store);if(!a.ok)return a.resp;if(!b||!isNonEmptyString(b.device_id,128)||!store.getDevice(b.device_id,a.claims.sub))return error("invalid_v2_payload",400);const fetched=store.fetchWrappedMatterKeyForAccess({matter_handle:handle,org_id:a.claims.org_id,user_id:a.claims.sub,role:a.claims.role,device_id:b.device_id});if(!fetched.ok){const auditOrg=fetched.reason==="cross_org"?a.claims.org_id:store.getMatter(handle)?.org_id??a.claims.org_id;store.audit({org_id:auditOrg,actor_user_id:a.claims.sub,action:"matter.access.denied",target:handle,detail:{action:"key_fetch",reason:fetched.reason}});return error(fetched.reason==="walled"||fetched.reason==="not_member"?"forbidden":"matter_not_found",fetched.reason==="walled"||fetched.reason==="not_member"?403:404,fetched.reason==="inactive"?undefined:fetched.reason);}store.audit({org_id:a.claims.org_id,actor_user_id:a.claims.sub,action:"matter.access.granted",target:handle,detail:{action:"key_fetch",via:fetched.access}});if(!fetched.key)return error("not_published",404);store.audit({org_id:a.claims.org_id,actor_user_id:a.claims.sub,action:"matter.keys.fetch",target:handle,detail:{op:"key_fetch",epoch:fetched.epoch}});return json({epoch:fetched.epoch,wrapped_key_b64:fetched.key.wrapped_key_b64}); }
export async function handleMatterMine(req:Request,store:Store):Promise<Response> { if(await readStrictV2Payload(req,v2BodyKeys("matterMine"))===null)return error("invalid_v2_payload",400);const a=authSeat(req,store);if(!a.ok)return a.resp;return json({matters:store.listMatterMembershipsForUser(a.claims.sub,a.claims.org_id)}); }
