import { useEffect, useState } from 'react';
import { FileSearch } from 'lucide-react';
import { Button } from '@/ui/button';
import { acceptDocumentExtractionProposal, dismissDocumentExtractionProposal, type DocumentExtractionAcceptResult } from '@/platform/intake/documentExtractionAccept';
import { intakeFactList, type MaskedClientFact } from '@/platform/intake/factsStore';
import { documentExtractionProposalGetForAccept, documentExtractionProposalList, isDocumentExtractionProposalItemSelectable, type DocumentExtractionProposalRecord } from '@/platform/intake/documentExtractionProposalStore';
import type { FactValue } from '@/platform/intake/types';
import { DocumentExtractionReviewModal } from './DocumentExtractionReviewModal';

export interface DocumentExtractionProposalCardProps { matterId: string; advisorId: string; onAccepted?: (result: DocumentExtractionAcceptResult) => void; }
function defaults(proposal: DocumentExtractionProposalRecord): Set<string> { return new Set(proposal.items.filter((row) => row.confidence === 'high' && row.checkedByDefault && isDocumentExtractionProposalItemSelectable(row)).map((row) => row.id)); }
export function DocumentExtractionProposalCard({ matterId, advisorId, onAccepted }: DocumentExtractionProposalCardProps) {
  const [proposals, setProposals] = useState<DocumentExtractionProposalRecord[]>([]); const [review, setReview] = useState<DocumentExtractionProposalRecord | null>(null); const [facts, setFacts] = useState<MaskedClientFact[]>([]); const [selected, setSelected] = useState<Set<string>>(new Set()); const [amounts, setAmounts] = useState<Record<string, string>>({}); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const load = () => { void documentExtractionProposalList(matterId).then(setProposals).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Could not load document facts.')); };
  useEffect(() => { load(); }, [matterId]);
  const open = async (summary: DocumentExtractionProposalRecord) => { try { const [full, activeFacts] = await Promise.all([documentExtractionProposalGetForAccept(summary.proposalId), intakeFactList(matterId)]); setReview(full); setFacts(activeFacts); setSelected(new Set([...defaults(full)].filter((rowId) => { const row = full.items.find((candidate) => candidate.id === rowId); return !activeFacts.some((fact) => fact.matter_id === full.matterId && fact.subject === row?.subject && fact.kind === row?.kind && fact.status === 'active'); }))); setAmounts(Object.fromEntries(full.items.filter((row) => row.value?.t === 'money').map((row) => [row.id, String((row.value as Extract<FactValue, { t: 'money' }>).v.amount)]))); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not open document review.'); } };
  const finalValues = (): Record<string, FactValue> => Object.fromEntries(Object.entries(amounts).flatMap(([id, amount]) => { const row = review?.items.find((candidate) => candidate.id === id); const parsed = Number(amount); if (!row?.value || row.value.t !== 'money' || !Number.isFinite(parsed) || parsed < 0) return []; return [[id, { t: 'money', v: { amount: parsed, currency: row.value.v.currency } } as FactValue]]; }));
  const approve = async () => { if (!review) return; setBusy(true); setError(''); try { const result = await acceptDocumentExtractionProposal({ proposalId: review.proposalId, selectedRowIds: [...selected], advisorId, finalValues: finalValues() }); onAccepted?.(result); if (result.status === 'accepted') { setReview(null); load(); } else { setReview(null); load(); setError(result.errors.join('; ') || 'Some facts still need review.'); } } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not approve document facts.'); } finally { setBusy(false); } };
  const dismiss = async () => { if (!review) return; setBusy(true); try { await dismissDocumentExtractionProposal({ proposalId: review.proposalId, advisorId }); setReview(null); load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not dismiss document facts.'); } finally { setBusy(false); } };
  if (!proposals.length && !error) return null;
  return <section data-testid="document-extraction-proposal-card" style={{ border: '1px solid var(--kp-warning-line)', borderRadius: 8, background: 'var(--kp-warning-bg)', padding: 14, display: 'grid', gap: 10 }}><div style={{ display: 'flex', alignItems: 'center', gap: 8 }}><FileSearch aria-hidden size={17} style={{ color: 'var(--kp-warning)' }} /><div><h3 style={{ margin: 0, fontSize: 14, fontWeight: 800, color: 'var(--kp-navy)' }}>Facts found in documents</h3><p style={{ margin: '4px 0 0', color: 'var(--color-muted-foreground)', fontSize: 12 }}>Review the page and quote first. Facts are saved only when you approve them.</p></div></div>{error ? <div style={{ color: 'var(--kp-danger)', fontSize: 12 }}>{error}</div> : null}{proposals.map((proposal) => <div key={proposal.proposalId} style={{ borderTop: '1px solid var(--kp-warning-line)', paddingTop: 10, display: 'flex', justifyContent: 'space-between', gap: 10, alignItems: 'center' }}><div style={{ color: 'var(--kp-navy)', fontSize: 13 }}>{proposal.items.length} proposed fact{proposal.items.length === 1 ? '' : 's'} from a filed document</div><Button type="button" variant="outline" size="sm" onClick={() => { void open(proposal); }}>Review</Button></div>)}{review ? <DocumentExtractionReviewModal proposal={review} selectedIds={selected} facts={facts} finalAmounts={amounts} onToggle={(id) => setSelected((current) => { const next = new Set(current); next.has(id) ? next.delete(id) : next.add(id); return next; })} onFinalAmountChange={(id, value) => setAmounts((current) => ({ ...current, [id]: value }))} onAccept={() => { void approve(); }} onDismiss={() => { void dismiss(); }} onClose={() => setReview(null)} accepting={busy} dismissing={busy} /> : null}</section>;
}
