#!/usr/bin/env node
// Build script for @projelli/plugin-api.
//
// Strategy: copy the relevant app source type files into the package's own
// `src/_app-types/` tree, run tsc, and emit a flat `dist/` with `index.d.ts`
// at the top. This avoids tsc's rootDir constraint when re-exporting types
// from outside the package, and produces a distribution that has no
// references to paths outside of `dist/`.

import { mkdirSync, copyFileSync, readFileSync, writeFileSync, rmSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(__dirname, '..');
const repoRoot = resolve(pkgRoot, '..', '..');

const stagingDir = resolve(pkgRoot, 'src', '_app-types');
const distDir = resolve(pkgRoot, 'dist');

// Files copied verbatim from app source. Update this list if the plugin types
// gain new dependencies.
const filesToCopy = [
  { from: 'src/types/plugin.ts', to: 'plugin.ts' },
  { from: 'src/types/workspace.ts', to: 'workspace.ts' },
];

function clean() {
  rmSync(stagingDir, { recursive: true, force: true });
  rmSync(distDir, { recursive: true, force: true });
}

function stage() {
  mkdirSync(stagingDir, { recursive: true });
  for (const { from, to } of filesToCopy) {
    const src = resolve(repoRoot, from);
    if (!existsSync(src)) {
      throw new Error(`Missing source file: ${src}`);
    }
    const dst = resolve(stagingDir, to);
    let contents = readFileSync(src, 'utf8');
    // Rewrite the workspace import in plugin.ts so it resolves locally.
    contents = contents.replace(
      /from '@\/types\/workspace'/g,
      "from './workspace'",
    );
    writeFileSync(dst, contents, 'utf8');
  }
}

function writeEntry() {
  const entry = resolve(pkgRoot, 'src', 'index.ts');
  writeFileSync(
    entry,
    `// Auto-generated by scripts/build.mjs. Do not edit by hand.
//
// Re-exports the canonical Projelli plugin types. The source of truth lives
// in the app at src/types/plugin.ts; the build script copies the relevant
// files into src/_app-types/ before invoking tsc.

export type {
  PluginAPI,
  PluginManifest,
  PluginManifestAuthor,
  PluginPermission,
  ToolbarButtonSpec,
  SidebarPanelSpec,
  SettingsPageSpec,
  SettingsPageFieldSpec,
  CommandSpec,
  PluginEditorRange,
  PluginEditorSelection,
  PluginAIInvokeOptions,
  PluginNetworkResponse,
  PluginModule,
  PluginStatus,
  PluginInstance,
} from './_app-types/plugin';

export type { FileNode } from './_app-types/workspace';
`,
    'utf8',
  );
}

function compile() {
  const result = spawnSync(
    'npx',
    ['tsc', '-p', resolve(pkgRoot, 'tsconfig.json')],
    { stdio: 'inherit', cwd: pkgRoot },
  );
  if (result.status !== 0) {
    throw new Error('tsc failed');
  }
}

clean();
stage();
writeEntry();
compile();
console.log('@projelli/plugin-api: build complete');
