import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { acceptDocumentExtractionProposal } from './documentExtractionAccept';
import { setIntakeDocumentExtractionAuditEmitter } from './documentExtractionAudit';
import { clearInMemoryDocumentExtractionQueuesForTests, documentExtractionProposalGetForAccept, documentExtractionProposalList, documentExtractionProposalSave, documentExtractionStableKey, stableDocumentExtractionProposalId, type DocumentExtractionProposalInput, type DocumentExtractionProposalRecord } from './documentExtractionProposalStore';
import type { MaskedClientFact } from './factsStore';

function input(): DocumentExtractionProposalInput { const ids = { matterId: 'matter-1', requestId: 'request-1', intakeId: 'intake-1', sourcePath: 'Clients/A/income.pdf' }; return { proposalId: stableDocumentExtractionProposalId(ids), stableKey: documentExtractionStableKey(ids), ...ids, items: [{ id: 'income-row', subject: 'primary', kind: 'income_annual', value: { t: 'money', v: { amount: 120000, currency: 'USD' } }, displayValue: 'USD 120000', sensitivity: 'confidential', source: { kind: 'document', path: ids.sourcePath, page: 2, snippet: 'Annual income: $120,000', extraction: 'text' }, confidence: 'high', reason: 'Printed annual income.', checkedByDefault: true }, { id: 'low-row', subject: 'primary', kind: 'spending_monthly', value: { t: 'money', v: { amount: 2000, currency: 'USD' } }, displayValue: 'USD 2000', sensitivity: 'confidential', source: { kind: 'document', path: ids.sourcePath, page: 3, snippet: 'Monthly total: $2,000', extraction: 'text' }, confidence: 'low', reason: 'Printed total.', checkedByDefault: false }] }; }
describe('document extraction proposal queue', () => {
  beforeEach(() => clearInMemoryDocumentExtractionQueuesForTests());
  afterEach(() => setIntakeDocumentExtractionAuditEmitter(null));
  it('is idempotent and masks list reads while keeping full review data behind a matching client check', async () => { await documentExtractionProposalSave(input()); await documentExtractionProposalSave({ ...input(), proposalId: 'other' }); const [listed] = await documentExtractionProposalList('matter-1'); expect(listed).toBeDefined(); expect(JSON.stringify(listed)).not.toContain('Annual income: $120,000'); expect(listed?.items[0]?.value).toBeUndefined(); expect(listed?.items[0]?.source.snippet).toBe(''); await expect(documentExtractionProposalGetForAccept(input().proposalId, 'matter-2')).rejects.toThrow('not found'); const full = await documentExtractionProposalGetForAccept(input().proposalId, 'matter-1'); expect(full.items[0]?.source.snippet).toBe('Annual income: $120,000'); expect(full.items[0]?.value).toBeDefined(); });
  it('writes nothing before an explicit approval and requires intent audit before a fact', async () => { const proposal = { ...input(), status: 'pending', completedRows: [], createdAt: '2026-07-10T00:00:00.000Z', updatedAt: '2026-07-10T00:00:00.000Z' } as DocumentExtractionProposalRecord; const upsert = vi.fn().mockResolvedValue({ fact_id: 'fact-1' } as MaskedClientFact); setIntakeDocumentExtractionAuditEmitter((entry) => entry.metadata['phase'] === 'intent' ? Promise.reject(new Error('audit offline')) : Promise.resolve()); await expect(acceptDocumentExtractionProposal({ proposalId: proposal.proposalId, selectedRowIds: ['income-row'], advisorId: 'advisor-1', getProposal: async () => proposal, upsertFact: upsert })).rejects.toThrow('audit offline'); expect(upsert).not.toHaveBeenCalled(); });
  it('writes exact document provenance only after intent audit', async () => { const proposal = { ...input(), status: 'pending', completedRows: [], createdAt: '2026-07-10T00:00:00.000Z', updatedAt: '2026-07-10T00:00:00.000Z' } as DocumentExtractionProposalRecord; const order: string[] = []; const upsert = vi.fn(() => { order.push('fact'); return Promise.resolve({ fact_id: 'fact-1' } as MaskedClientFact); }); setIntakeDocumentExtractionAuditEmitter((entry) => { order.push(`audit:${String(entry.metadata['phase'])}`); return Promise.resolve(); }); await acceptDocumentExtractionProposal({ proposalId: proposal.proposalId, selectedRowIds: ['income-row'], advisorId: 'advisor-1', getProposal: async () => proposal, upsertFact: upsert, markRowCompleted: vi.fn().mockResolvedValue(proposal), setProposalStatus: vi.fn().mockResolvedValue(proposal) }); expect(order).toEqual(['audit:intent', 'fact', 'audit:outcome']); expect(upsert).toHaveBeenCalledWith(expect.objectContaining({ verification: 'document_verified', provenance: expect.objectContaining({ channel: 'doc_extraction', confirmed_by: 'advisor-1', entered_by: 'advisor-1', source_ref: expect.stringContaining('document:v1:') }) })); });
  it('refuses an off-contract final value before any fact write', async () => { const proposal = { ...input(), status: 'pending', completedRows: [], createdAt: '2026-07-10T00:00:00.000Z', updatedAt: '2026-07-10T00:00:00.000Z' } as DocumentExtractionProposalRecord; const upsert = vi.fn(); await expect(acceptDocumentExtractionProposal({ proposalId: proposal.proposalId, selectedRowIds: ['income-row'], advisorId: 'advisor-1', finalValues: { 'income-row': { t: 'string', v: 'not money' } }, getProposal: async () => proposal, upsertFact: upsert })).rejects.toThrow('money amount'); expect(upsert).not.toHaveBeenCalled(); });
});
