export {
  bootstrapSelectionAuthorityFromPersistedFollower,
  issueAllMattersScopeSelection,
  issueMatterScopeSelection,
  issueRehydratedSelection,
  issueSharedClientSelection,
  readAuthoritativeMatterScope,
  readSharedClientContext,
  rehydrateSelectionHint,
  replaceCanonicalHouseholdDirectory,
  requestClearClientSelection,
  requestMatterScopeSelection,
  requestRehydratedSelection,
  requestSharedClientSelection,
  resolveCanonicalHouseholdClassification,
  resolveCanonicalHouseholdMatter,
  useClientContextStore,
  type CanonicalHouseholdRef,
  type ClientContextState,
  type CrmProviderId,
  type FollowerStatus,
  type HouseholdClassification,
  type MatterScopeSelection,
  type MatterScopeSelectionResult,
  type PersistedSelectionHint,
  type RehydratedSelectionInput,
  type RehydratedSelectionResult,
  type SealedClientBoundary,
  type SealedClientSelectionClassification,
  type SealedMatterScopeSelection,
  type SealedRehydratedSelectionClassification,
  type SelectionResult,
  type SharedClientContextAdapter,
  type SharedClientIdentity,
  type SharedClientSelectionInput,
} from './clientContextStore';
